### ISSUE TITLE
Can't click through to the file

### ISSUE THREAD

**Issue by jamie-pate** [ameyp/CscopeSublime#21]
Being able to search scope is really nice, but when the results menu pops up I can't click through to the file it found.

**Comment by vanrijn** [comment]
I just checked and ST3 still does not support this. The problem is that there's no context settings for mouse bindings. So one and only one plugin can override the double-click handler like @redhat008 did above, and if more than one plugin does, it's a crap-shoot as to which plugin actually gets the event. There's nothing we can do here. We're doing the best we can by navigating to cscope results via keyboard <Enter> key.
