### ISSUE TITLE
Display Cscope result in the other column in 2-column layout

### ISSUE THREAD

**Issue by hwyuan** [ameyp/CscopeSublime#41]
Thanks a lot for developing this handy tool. 

(Maybe I missed something, but..) I'm wondering if it is possible to display the Cscope results on the other column in the 2-column layout. Currently, I always manually drag the Cscope results to the right column if the looked up variable is on the left column. 

Thanks in advance. : )

**Comment by vanrijn** [comment]
Hi @hwyuan. Is there another plugin that works in the way that you're talking about? I am not sure how we would do this since the user can change the layout to be whatever they want with Sublime Text. They can have up to 4 columns and multiple rows too.

I don't think we can make any assumptions about either how the user has their layouts configured, or in what column they would want us to create the output window. I'm totally open if you want to code this up and send a pull request for this. But I don't know that it's possible and I'm concerned that if it is possible, the complexity is pretty high for letting the user configure how this would work.

**Comment by vanrijn** [comment]
So, to be clear, I don't have time to do this. I am open to looking at pull requests if anyone wants to implement this in a way that does not make any assumptions about the view layout or how many columns or rows the user is using. I'll leave this open for a while to see if anyone wants to send a patch and pull request.

**Comment by vanrijn** [comment]
Yeah, sorry, I'm going to close this. Nobody is contributing patches for this and I don't think there's a foolproof way of implementing this in ST3.
