### ISSUE TITLE
The search results doesn't support jumping to the matches.

### ISSUE THREAD

**Issue by lvlvturancao** [ameyp/CscopeSublime#54]
For example, when I use seaching cscope for functions of calling this function, I'd like the search result support to jump to destinations like Sublime Text 3's own seach in files result, you can double click the line number to jump to the destination in the result page.
Sorry for my poor English expression and expect you can improve the plugin, thanks!

**Comment by vanrijn** [comment]
Actually, it does support this. If you click on the line  that you want to go to and then press <Enter>, the plugin will take you to that place in the file. I wish we could support double-clicking like ST's built-in find functionality does, but this is not currently possible due to the way event handling works in ST. See also issue #21.
